#!/bin/bash

echo "Optional Applications Installation Script"

# Function to handle user choices for optional packages
install_optional() {
    local prompt="$1"
    local packages_pacman=("${!2}")
    local packages_yay=("${!3}")
    read -p "$prompt [Y/n]: " choice
    if [[ "$choice" == [Yy]* ]] || [[ -z "$choice" ]]; then
        if [ ${#packages_pacman[@]} -ne 0 ]; then
            echo "Installing packages via pacman: ${packages_pacman[@]}"
            sleep 3
            sudo pacman -S --needed "${packages_pacman[@]}"
        fi
        if [ ${#packages_yay[@]} -ne 0 ]; then
            echo "Installing packages via yay: ${packages_yay[@]}"
            sleep 3
            yay -S "${packages_yay[@]}"
        fi
    fi
}

# DAW Apps
daw_apps_pacman=()
daw_apps_yay=(reaper qpwgraph yabridge yabridgectl realtime-privileges)
install_optional "Do you want to install DAW apps?" daw_apps_pacman[@] daw_apps_yay[@]

# DAW Plugins
daw_plugins_pacman=()
daw_plugins_yay=(pro-audio lv2-plugins vst-plugins vst3-plugins)
install_optional "Do you want to install DAW plugins?" daw_plugins_pacman[@] daw_plugins_yay[@]

# Web Dev
web_dev_pacman=(filezilla bluefish)
web_dev_yay=()
install_optional "Do you want to install web development tools?" web_dev_pacman[@] web_dev_yay[@]

# Image and Video Editing
image_video_pacman=(obs-studio kdenlive gimp)
image_video_yay=()
install_optional "Do you want to install image and video editing tools?" image_video_pacman[@] image_video_yay[@]

# Communication
communication_pacman=(thunderbird irssi signal-desktop)
communication_yay=()
install_optional "Do you want to install communication tools?" communication_pacman[@] communication_yay[@]

echo "Optional applications installation script completed."
